### ISSUE TITLE
when I run npm run dev i show these errors

### ISSUE THREAD

**Issue by malisting** [0xProject/0x-starter-project#1]
when I run npm run dev i show these errors 0xJsStarterProject@0.0.0 dev C:\Users\hicham\Desktop\project\0x
npm run build; node ./lib/index.js

m ERR! missing script: build;

m ERR! A complete log of this run can be found in:
m ERR! C:\Users\hicham\AppData\Roaming\npm-cache\_logs\2018-01-12T16_07_12
80Z-debug.log
m ERR! code ELIFECYCLE
m ERR! errno 1
m ERR! 0xJsStarterProject@0.0.0 dev: `npm run build; node ./lib/index.js`
m ERR! Exit status 1
m ERR!
m ERR! Failed at the 0xJsStarterProject@0.0.0 dev script.
m ERR! This is probably not a problem with npm. There is likely additional log
ng output above.

m ERR! A complete log of this run can be found in:
m ERR! C:\Users\hicham\AppData\Roaming\npm-cache\_logs\2018-01-12T16_07_12
58Z-debug.log

**Comment by dekz** [comment]
hey @malisting 

It appears that you're running this on windows and the semicolon is not being interpreted correctly in your shell environment. Here is the intention of the [semicolon](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/----command-separator-).

Could you try running the commands individually, it has been a long time since I have done much development on Windows.
```
npm run build
```
then
```
node ./lib/index.js
```

**Comment by natez1** [comment]
I'm running windows and I having the same issue, I unable to run
` `Npm run download_snapshot``

npm ERR! 0xJsStarterProject@0.0.0 dev: `npm run build; node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 0xJsStarterProject@0.0.0 dev script.
&
`npm run dev`
npm ERR! 0xJsStarterProject@0.0.0 dev: `npm run build; node ./lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 0xJsStarterProject@0.0.0 dev script.

**Comment by dekz** [comment]
hi @natez1 

We will investigate the issue on windows shortly. In the mean time, you can run the commands individually.

```
npm run build
node ./lib/index.js
```

**Comment by themandalore** [comment]
Is there any sort of system dependencies for 0x.js?  It seems I need quite the litany of dev-ops tools installed and updated to the brim.  Even if it is only LInux tested with node 9+, it would be helpful to know

**Comment by dekz** [comment]
This project has been updated to support Windows. Please let me know if you experience any further issues. I was able to successfully get it all running on an AWS Windows machine.
