### ISSUE TITLE
Module ''bn.js'' has no exported member 'BigNumber'.

### ISSUE THREAD

**Issue by leoplct** [0xProject/0x-starter-project#11]
yarn run order_actions

```
yarn run v1.6.0
$ run-s build tutorial:order_actions
$ tsc
node_modules/web3/types.d.ts(1,10): error TS2305: Module ''bn.js'' has no exported member 'BigNumber'.
node_modules/web3/types.d.ts(1,27): error TS2497: Module ''bn.js'' resolves to a non-module entity and cannot be imported using this construct.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fabioberger** [comment]
@leoplct, did you run: `yarn install`?

**Comment by leoplct** [comment]
Yes,
**yarn.lock**

> "@0xproject/utils@^0.5.2":
>   version "0.5.2"
>   resolved "https://registry.yarnpkg.com/@0xproject/utils/-/utils-0.5.2.tgz#02ce0a920437db0a15d059e8c6c70fa33e9c3860"
>   dependencies:
>     "@0xproject/types" "^0.6.1"
>     "@0xproject/typescript-typings" "^0.2.0"
>     "@types/node" "^8.0.53"
>     bignumber.js "~4.1.0"
>     ethers-contracts "^2.2.1"
>     js-sha3 "^0.7.0"
>     lodash "^4.17.4"
>     web3 "^0.20.0"

**package.json**

```
  "dependencies": {
        "0x.js": "0.36.3",
        "@0xproject/connect": "^0.6.10",
        "@0xproject/tslint-config": "^0.4.16",
        "@0xproject/utils": "^0.5.2",
        "@types/underscore": "^1.8.8",
        "bignumber.js": "^7.0.1",
        "body-parser": "^1.18.2",
        "express": "^4.16.2",
        "web3": "0.20.2",
        "websocket": "^1.0.25"
```

**Comment by fabioberger** [comment]
You must have accidentally installed an additional version of `web3`. Please check your `node_modules` folder because version 0.20.2 does not include a `node_modules/web3/types.d.ts` file.

**Comment by leoplct** [comment]
I deleted and install it again following wiki tutorial. Same problem

**Comment by leoplct** [comment]
Solved deleting this folder ../../../node_modules/
