### ISSUE TITLE
Clone the repo issue

### ISSUE THREAD

**Issue by rajqumar** [0xProject/0x-starter-project#12]
`git clone git@github.com:0xProject/0x.js-starter-project.git
`
When I run this command I am getting the below error

**Cloning into '0x.js-starter-project'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.**

I tried running with sudo, doesn't work either.
However cloning this https://github.com/0xProject/0x-starter-project.git worked, but the problem I was facing from the one mentioned in the 0x wiki command.

**Comment by fabioberger** [comment]
Thanks for the heads up! I've gone ahead and updated the wiki, the previous repo no longer exists.
