### ISSUE TITLE
Exports error

### ISSUE THREAD

**Issue by salman18693** [0xProject/0x-starter-project#14]
While importing 0x.js using script in index html it shows Uncaught ReferenceError: exports is not defined at 0x.js:43
Object.defineProperty(exports, "__esModule", { value: true }); // shows error at this line

**Comment by salman18693** [comment]
@fabioberger Yes, it is a issue with the 0x-starter-project.

**Comment by dekz** [comment]
Closing as this does not seem to be an issue with the starter project (as there is no web/HTML component). If we are wrong let us know by opening another issue.
