### ISSUE TITLE
How to Unwrap ETH

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-starter-project#15]
Hey,

I was just wondering, how can we perform reverse of Wrapping ETH, that means converting WETH to ETH again through code ?

Please Suggest.
Thanks

**Comment by fabioberger** [comment]
You can use `0x.js`'s [zeroEx.etherToken.withdrawAsync](https://0xproject.com/docs/0x.js#etherToken-withdrawAsync) function.

**Comment by narmadhasugumar** [comment]
Hi i tried to WETH to ETH from my local testrpc but i am getting error like this which i mentioned below please help me what will be the reason ???

![image](https://user-images.githubusercontent.com/29334263/45092110-1abee780-b132-11e8-9dcc-22ffe66f3067.png)
![image](https://user-images.githubusercontent.com/29334263/45092131-23afb900-b132-11e8-9f0d-b7db67e2469c.png)

**Comment by dekz** [comment]
@narmadhasugumar did you modify any code, if so can you post any changes?

**Comment by narmadhasugumar** [comment]
Hi @dekz first of all thank you for the reply :)
Yes I Slightly changed but i am not sure whether i correctly did or not. 
and
Yes i Connected with testing account which has nearly 50 WETH

Here is my coding what i did ..
    
    const wethTokenInfo = await zeroEx.tokenRegistry.getTokenBySymbolIfExistsAsync('WETH');
    const WETH_ADDRESS = wethTokenInfo.address;
    var addresses = await zeroEx.getAvailableAddressesAsync();
    const wethOwnerAddress = addresses[0]
    const etherwithdraw = await zeroEx.token.getBalanceAsync(WETH_ADDRESS, wethOwnerAddress);
    const withdrawTxHashes = await zeroEx.etherToken.withdrawAsync(WETH_ADDRESS, etherwithdraw, wethOwnerAddress);

**Comment by narmadhasugumar** [comment]
I tried Unwrap in 0x protocol https://www.0xproject.com/portal/weth even there it got an error like this 

** But it is my test mode

![image](https://user-images.githubusercontent.com/29334263/45135459-24416180-b1bd-11e8-851f-81cbc37e923c.png)

**Comment by narmadhasugumar** [comment]
Please Help me @dekz @fabioberger

**Comment by rhrahul** [comment]
@narmadhasugumar , Do you have enough gas (I mean ETH) in account to perform transaction ?

**Comment by narmadhasugumar** [comment]
Yes I have 43 ETH and 52 WETH in my Testnet @rhrahul

**Comment by rhrahul** [comment]
Can you console.log value of `etherwithdraw` @narmadhasugumar

**Comment by narmadhasugumar** [comment]
Here is the etherWithdraw console.log value @rhrahul  
![image](https://user-images.githubusercontent.com/29334263/45211544-364ffc80-b2b0-11e8-87e1-1a26c5430d80.png)

**Comment by rhrahul** [comment]
That looks fine, 
Can you try with Ropsten/Kovan/Rinkeby Network ?

**Comment by narmadhasugumar** [comment]
@rhrahul  Hey wow thanks its working in Ropsten Network but not in localhost don't no the reason.
Can we fix particular amount that we want to unwrap that means 
if i am having 5WETh and to Unwrap 2 ETH .
Can you help me in this please
and thank you much for the suggestion @rhrahul

**Comment by narmadhasugumar** [comment]
Thanks @rhrahul 
I did the same thing in localhost i got error message so i tried new method. 
Its working thank you much again
