### ISSUE TITLE
v2 support

### ISSUE THREAD

**Issue by MichaelDragan** [0xProject/0x-starter-project#16]
Hey there, was just wondering if there is going to be a starter-project using version 2 of the 0x protocol.

**Comment by dekz** [comment]
@MichaelDragan please take a look at the v2 branch:
https://github.com/0xProject/0x-starter-project/tree/v2

Let me know if you run into any issues. We will update this to also include a relayer serving up an SRA endpoint.

**Comment by dekz** [comment]
This is now merged into master so closing this issue! Let me know if you have any problems or requests for examples!
