### ISSUE TITLE
How to lock the token 

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#20]
Hi,

I just wanted to know how to lock the token 
Ex: We are unlocking the token using 

### 0x.js

 **zeroEx.token.setUnlimitedProxyAllowanceAsync** vise versa as a revert process i want to lock the token 
Thanks in advance

**Comment by fabioberger** [comment]
@narmadhasugumar to reverse the process set the allowance to 0. You can do this using:

```
zeroEx.token.setProxyAllowanceAsync(new BigNumber(0));
```

**Comment by narmadhasugumar** [comment]
This is for locking the token?..
zeroEx.token.setProxyAllowanceAsync(new BigNumber(0));

And if i want to get the unlocked contract tokens and loked contract tokens dynamically how to get that one ?

**Comment by narmadhasugumar** [comment]
How to get 
const zeroEx = new ZeroEx(web3js.currentProvider, { networkId: networkId })
networkid dynamically?

**Comment by narmadhasugumar** [comment]
> @narmadhasugumar to reverse the process set the allowance to 0. You can do this using:
> 
> ```
> zeroEx.token.setProxyAllowanceAsync(new BigNumber(0));
> ```
> Or in-case you are using the V2 0x.js library (>= 1.0.1):
> 
> ```
> contractWrappers.erc20Token.setProxyAllowanceAsync(new BigNumber(0));
> ```

by locking it won't sign into metamask for permission?

**Comment by narmadhasugumar** [comment]
**_First Issue:_**
I just want to **UNLOCK and LOCK** the token, here in below image WETH can locked & unlocked, so i am able to **UNLOCK** the token but unable to **LOCK** the token, and unable to get the UNLOCKED tokens from. Just want to know how to **LOCK** and how to get the **UNLOCKED list of tokens**
![image](https://user-images.githubusercontent.com/29334263/45624419-eb03ce00-baa7-11e8-9173-d0100924a51c.png).


**_SECOND ISSUE:_**
Is we have any possibilities to get the networkId dynamically instead of mentioning the networkid : 1 (statically)

Are you getting my issue @fabioberger

**Comment by fabioberger** [comment]
@narmadhasugumar the UI showing "locked" and "unlocked" is a simplification of the reality. In reality, users are setting and unsetting their addresses' allowance to the 0x proxy contract. Locked is when the allowance set is `0`, unlocked is when it's set to the largest possible allowance amount `2^256-1`.

Setting allowances always requires the user to send a TX to the network.

**Comment by narmadhasugumar** [comment]
ok thank you @fabioberger for the explanation you gave for locking and unlocking i will try 

```

> below code is for unlock
>  await Promise.all(addresses.map(address => {
>       return zeroEx.token.setUnlimitedProxyAllowanceAsync(WETH_ADDRESS, address)
>  }))
> 
> and, for lock
> zeroEx.token.setProxyAllowanceAsync(new BigNumber(0))

```

**Comment by fabioberger** [comment]
Np. Yes, that is correct but be sure to also await that those transactions are mined (you can use: https://0xproject.com/docs/web3-wrapper#Web3Wrapper-awaitTransactionSuccessAsync).

Good luck!

**Comment by narmadhasugumar** [comment]
ok thankyou @fabioberger .

One more think i want to know, 

```
const zeroExConfig: ZeroExConfig = {
       networkId: 50, // testrpc
};
```

Is this the only way to get networkid directly, we cnt't take dynamically ? I am new to this platform so have so many doubts

**Comment by fpChan** [comment]
> **_First Issue:_**
> I just want to **UNLOCK and LOCK** the token, here in below image WETH can locked & unlocked, so i am able to **UNLOCK** the token but unable to **LOCK** the token, and unable to get the UNLOCKED tokens from. Just want to know how to **LOCK** and how to get the **UNLOCKED list of tokens**
> ![image](https://user-images.githubusercontent.com/29334263/45624419-eb03ce00-baa7-11e8-9173-d0100924a51c.png).
> 
> **_SECOND ISSUE:_**
> Is we have any possibilities to get the networkId dynamically instead of mentioning the networkid : 1 (statically)
> 
> Are you getting my issue **@fabioberger**

how do you know the state of Token ? like WETH is locked , is there a function in 0x.js?

**Comment by narmadhasugumar** [comment]
Yes, @fpChan it is called Checking the allowance status of the tokens, Here below i mentioned 
`const allowance = await contractWrappers.erc20Token.getProxyAllowanceAsync(tokenAddress, address)`
