### ISSUE TITLE
how to reterive the locked and unloked token details

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#22]
What is the way to retrieve the token details and make them locked and unloked

**Comment by dekz** [comment]
Locked/unlocked is just a UI/UX concept representing allowances for the Transfer Proxy. 

[erc20Token.getProxyAllowanceAsync](https://0xproject.com/docs/contract-wrappers#ERC20TokenWrapper-getProxyAllowanceAsync) > 0 would be "unlocked" and == 0 would be "locked"

**Comment by narmadhasugumar** [comment]
Thanks worked for me @dekz
