### ISSUE TITLE
How to Change to Token Balance automactically if Account changes in Metamask

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#23]
If i change the account in **Metamask** it doesnt change the **_TOKEN BALANCE_** Automatically Can any one help in this issue

**Comment by dekz** [comment]
This is probably something for the 0x-codesandbox repo. You need to poll for changes and update your state. Here is an [example from the 0x-codesandbox repo](https://github.com/0xProject/0x-codesandbox/blob/master/src/components/account.tsx#L35).
