### ISSUE TITLE
Missing code for validating order is fillable before calling fillOrder

### ISSUE THREAD

**Issue by labsterx** [0xProject/0x-starter-project#237]
In src/scenarios/fill_order_erc20.ts, originally there was code that validates the order is fillable before calling fillOrder. However, this part was missing in the new version. I understand the function was moved to OrderUtils, but i’d be nice to add this function back so that people can see how to use it.

**Comment by dekz** [comment]
This can now be [found here](https://github.com/0xProject/0x-starter-project/blob/master/src/scenarios/fill_order_sra.ts#L113-L120).
