### ISSUE TITLE
How to get the data if Error: MetaMask Tx Signature: User denied transaction signature.

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#25]
How to get the status if Error: MetaMask Tx Signature: User denied transaction signature. in DAPP to do the further process

**Comment by dekz** [comment]
hey @narmadhasugumar are you seeing 0x.js swallowing these errors? Or is the txHash coming back as `undefined`?

**Comment by narmadhasugumar** [comment]
I am trying to get status 
![image](https://user-images.githubusercontent.com/29334263/46651429-98589600-cbbd-11e8-8e9a-3a84da0e1db8.png)
if user click cancel. i get in console
![image](https://user-images.githubusercontent.com/29334263/46651585-246abd80-cbbe-11e8-9fb6-f5ade869a613.png)

**Comment by dekz** [comment]
@narmadhasugumar there is currently a bug in 0x.js which swallows this message. A fix will be out in the next release 0x.js 2.x

**Comment by narmadhasugumar** [comment]
Ok, that is not my problem its okay it it shows a message. 
I just want to fetch the **CANCEL** tx data, to notify to the user that **TRANSACTION CANCELLED**, so how to fetch it

**Comment by narmadhasugumar** [comment]
yes you are correct, thats what i am asking how to get it

**Comment by narmadhasugumar** [comment]
I didnt get the solution but you closed the issue ?Why @fabioberger

**Comment by fabioberger** [comment]
Ah sorry, I misunderstood your message. Did you mean you want to know whether a particular is cancelled? If so, use: [isCancelledAsync](https://0xproject.com/docs/0x.js#ExchangeWrapper-isCancelledAsync).

**Comment by varshakhandre14** [comment]
If the user rejects the transaction and you want to notify about this then you can check my code. Basically, if the user rejects the transaction, it returns transaction result as **undefined**.
```
ethereum.send({
      method: 'eth_sendTransaction',
      params: [{"from": accounts[0],
      "to": smartContractaddress,
      "gas": "0x2DC6C0", // 30400
      "gasPrice": "0x2540BE400", 
      "value": weitohex, // 2441406250
      "data": inputhex}],
      //from: web3.eth.accounts[0], // Provide the user's account to use.
      from: accounts[0],
    },function(err, transactionHash) {
      if (!err){
        console.log(transactionHash); 
        if(transactionHash.result !== undefined){
          document.getElementById('span_metalink').innerText="https://kovan.etherscan.io/tx/"+transactionHash.result;
          document.getElementById('span_metalink').href="https://kovan.etherscan.io/tx/"+transactionHash.result;
          document.getElementById('span_success').innerText = "Transaction Successfully Done!!!";
        }
        else{
          document.getElementById('span_success').innerText = "User denied transaction signature.";
        }
      }
    })
```

**Comment by mohamedtarek77** [comment]
this problem happened to me after many tries and errors  I tried to change my chain id  to the wallet that give me 31337 and it works 
![chain id](https://user-images.githubusercontent.com/68486188/178062969-a7bbce48-5ad5-4fca-b365-0642fc7c14d5.PNG)
![new chain id](https://user-images.githubusercontent.com/68486188/178062974-b61ce123-4909-42e0-85c4-904ba660b97c.PNG)
