### ISSUE TITLE
Mainnet rpcUrl 

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#26]
As i started using **0x version 2**.. i want to connect with **MAINNET_CONFIGS** can you please tell me the URL of **MAINNET** as 
ROPSTEN_CONFIGS =  **'https://ropsten.infura.io/'**
KOVAN_CONFIGS = **'https://kovan.infura.io/'**
MAINNET_CONFIGS = **?**

### 'https://mainnet.infura.io/' is this correct for **MAINNET**

**Comment by dekz** [comment]
yes that is correct
