### ISSUE TITLE
0x protocol version 2 Get token by symbol

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#27]
As we are using                                                                                                                                  
await zeroEx.tokenRegistry.getTokenBySymbolIfExistsAsync('WETH') this method is used in Verion v0 how to get this in verison v2 Can any one please help me in this ?

**Comment by dekz** [comment]
The token registry has been deprecated and is not available in 0x v2. You should create a mapping locally of these addresses for use in your dApp.
