### ISSUE TITLE
Place order in 0x V2

### ISSUE THREAD

**Issue by narmadhasugumar** [0xProject/0x-starter-project#28]
Getting error in console as INVALID_SIGNATURE. What mistake i did that it comes like this
![image](https://user-images.githubusercontent.com/29334263/46860516-38b4f180-ce2e-11e8-8e83-67184e283288.png)
Can any one help me in this

**Comment by GrantGochnauer** [comment]
I get the same error on my setup too. I’m using a custom erc 721 token and haven’t quite figured out what the source of the invalid signature is yet. Is there a way to get more information on why the signature was invalid?

**Comment by dekz** [comment]
@GrantGochnauer this starter project has a example of using ERC721.

It's hard to figure out and report to a user why a signature is invalid.

Here are the 3 common scenarios currently (and we're working towards reducing these edge cases):
* Metamask inconsistencies in their `eth_sign` implementation. In 0x.js there is `SignerType.Metamask` to help 0x.js figure out it needs to perform a work around.
* Order hash is calculated incorrectly when order values are `strings` not `BigNumbers`, this is fixed on master soon to be published.
* Using web3.js directly to sign (some providers spit out different formats for `v,r,s` values of an ec signature).

Easiest way to help us point you in the right direction:
* Paste the signature
* Paste the order and the order hash
* Share how you're reading/constructing an order and ensuring the amounts (and salt and expiry time) are all BigNumbers (see here for the [Order type](https://0xproject.com/docs/0xjs#types-Order)

**Comment by narmadhasugumar** [comment]
Sorry for the late response, this is my code
 ```
async function (orderType, QuoteTokenAddress, BaseTokenAddress, QuoteTokenDecimal, 
 BaseTokenDecimal) {
  var makerAssetAmount
  var takerAssetAmount
  var makerAssetData
  var takerAssetData

  const web3js = window.web3
  const provider = web3js.currentProvider

  const contractWrappers = new ContractWrappers(provider, { networkId: NETWORK_CONFIGS.networkId })
  if (typeof web3js !== 'undefined') {
    const relayerApiUrl = StaticLinks.relayerApiUrl
    const httpClient = new HttpClient(relayerApiUrl)

    const web3Wrapper = new Web3Wrapper(provider)
    const addresses = await web3Wrapper.getAvailableAddressesAsync()
    const maker = addresses[0]

    const price = new BigNumber(this.price)
    const amount = new BigNumber(this.amount)

      makerAssetAmount = (Web3Wrapper.toBaseUnitAmount(price, QuoteTokenDecimal) * amount).toString()
      takerAssetAmount = (Web3Wrapper.toBaseUnitAmount(amount, BaseTokenDecimal)).toString()
      makerAssetData = assetDataUtils.encodeERC20AssetData(QuoteTokenAddress)
      takerAssetData = assetDataUtils.encodeERC20AssetData(BaseTokenAddress)
   
    // Generate and expiration time and find the exchange smart contract address
    const randomExpiration = getRandomFutureDateInSeconds()
    const exchangeAddress = contractWrappers.exchange.getContractAddress()

    // Ask the relayer about the parameters they require for the order
    const orderConfigRequest = {
      exchangeAddress,
      makerAddress: maker,
      takerAddress: NULL_ADDRESS,
      expirationTimeSeconds: randomExpiration,
      makerAssetAmount,
      takerAssetAmount,
      makerAssetData,
      takerAssetData
    }

    const orderConfig = await httpClient.getOrderConfigAsync(orderConfigRequest, {
      networkId: NETWORK_CONFIGS.networkId
    })

    // Create the order
    const order = {
      salt: generatePseudoRandomSalt(),
      ...orderConfigRequest,
      ...orderConfig
    }
 
    // Generate the order hash and sign it
    const orderHashHex = orderHashUtils.getOrderHashHex(order)

    const signature = await signatureUtils.ecSignOrderHashAsync(
      provider,
      orderHashHex,
      maker,
      SignerType.Default
    )

    const signedOrder = { ...order, signature }
 
    // Validate this order
    const sadasd = await contractWrappers.exchange.validateOrderFillableOrThrowAsync(signedOrder)
    // Submit the order to the SRA Endpoint
    const eerter = await httpClient.submitOrderAsync(signedOrder, { networkId: NETWORK_CONFIGS.networkId })
  }
```

**Comment by dekz** [comment]
```typescript
const web3js = window.web3
const provider = web3js.currentProvider
...
   const signature = await signatureUtils.ecSignOrderHashAsync(
     provider,
     orderHashHex,
     maker,
     SignerType.Default
   )
```

If `window.web3` is provided by Metamask then you need to inform 0x of this (since Metamask has a non standard `eth_sign` implementation. We do this in the [codesandbox example](https://github.com/0xProject/0x-codesandbox/blob/master/src/components/zeroex_actions/create_order.tsx#L92).

```typescript
   const signature = await signatureUtils.ecSignOrderHashAsync(
     provider,
     orderHashHex,
     maker,
     SignerType.Metamask
   )
```

0x-starter-project uses `SignerType.Default` since the `MnemonicSubprovider` is a spec compliant implementation of `eth_sign`.

**Comment by dekz** [comment]
make sure all of your amounts are BigNumbers and not strings. Looks like the takerAssetAmount you are supplying is a string.

**Comment by narmadhasugumar** [comment]
Ya i changed into BigNumbers after that too i am getting this error 
`![image](https://user-images.githubusercontent.com/29334263/46902550-03b7a600-cee5-11e8-88f7-e9552f8bad0a.png)`

**Comment by dekz** [comment]
Where is that error originating from?

Can you paste the order and signature as well

**Comment by narmadhasugumar** [comment]
order
![image](https://user-images.githubusercontent.com/29334263/46902848-f6e98100-cee9-11e8-97c8-1a09807aa25e.png)

signature
0x1c35cf79db6768c953a10cff4d96f94eabfb76e969841a86a73185d8e3617e4ba8262828e72eebd8f31b85393cb687094f6faa63dc186b86cfd799e673a005532803

These above details are my order and signature

**Comment by dekz** [comment]
Your `makerAssetAmount` looks like it is still a string.

**Comment by narmadhasugumar** [comment]
Is that the problem but it has to make it to string

**Comment by narmadhasugumar** [comment]
https://github.com/0xProject/standard-relayer-api/blob/master/http/v2.md in this JSON all are mentioned as string only. then what problem i am facing so far

**Comment by dekz** [comment]
It is required to be a BigNumber when generating the order hash and signing
the order hash. If you use 0x connect it will serialize the order for you.
JSON has no native bignumber so when you send it via json is needs to be a
string. When interacting with 0xjs and order utils it needs to be a
BigNumber

**Comment by narmadhasugumar** [comment]
Ok..
When i try to connect with MAINNET it doesnt fetch the address. Here what will be the pbrolem
```
export const providerEngine = new Web3ProviderEngine()
providerEngine.addProvider(new RPCSubprovider('https://mainnet.infura.io/'))
providerEngine.start()
```

**Comment by dekz** [comment]
That provider engine config looks fine for **data** requests only (no accounts or signing), what do you mean by it doesn't `fetch the address`?

**Comment by dekz** [comment]
That's because you haven't configured it to point to a Signer, INFURA only supports data fetching.

See the [0x Codesandbox for an example](https://codesandbox.io/s/github/0xproject/0x-codesandbox)

```typescript
export const providerEngine = new Web3ProviderEngine()
providerEngine.addProvider(new SignerSubprovider(web3.currentProvider)) // add a signer i.e Metamask web3
providerEngine.addProvider(new RPCSubprovider('https://mainnet.infura.io/'))
providerEngine.start()
```

**Comment by narmadhasugumar** [comment]
If i try to connect with Ledger too will the above code work

**Comment by dekz** [comment]
You will need to use the Ledger subprovider to connect the ledger. There is a [Ledger example in our wiki](https://0xproject.com/wiki#Web3-Provider-Examples).

**Comment by narmadhasugumar** [comment]
ok ..
How to auto refresh if connected with metamask, metamask logged out account change and order place balance decrement

**Comment by narmadhasugumar** [comment]
Why i am getting error like this while placing the order in testrpc. i have 82 weth balance in am testnet
weth 3.2
zrx 9
![image](https://user-images.githubusercontent.com/29334263/47604538-dc022b00-da18-11e8-8475-39f5f5af7eac.png)
