### ISSUE TITLE
Error: INSUFFICIENT_TAKER_FEE_ALLOWANCE

### ISSUE THREAD

**Issue by renuseabhaya** [0xProject/0x-starter-project#53]
Getting  error as  "Error: INSUFFICIENT_TAKER_FEE_ALLOWANCE"  in latest code while running scenario:fill_order_sra,  hence fillOrder failed.

**Comment by dekz** [comment]
Thanks for reporting @renuseabhaya. Looks like the SRA server in the starter project has a takerFee of 1000. The `fill_order_sra` example doesn't handle being executed first, though it executed after `fill_order_fees` it should behave as expected. I'll make a change to handle `fill_order_sra` being ran as the first example.
